### ISSUE TITLE
Ajout_Clavier_Final

### ISSUE THREAD

**Issue by Arsene-Gery** [savaij/HN-2023-guesclin#29]
ajouter le clavier final utilisé pour la transcription.

**Comment by savaij** [comment]
Il y a quatre versions de clavier sur le git, ajoutées avec #19 

je vais éliminer les versions plus anciennes pour garder seulement le clavier final

**Comment by Arsene-Gery** [comment]
DONE - ajouté dans pull request #36

**Comment by Arsene-Gery** [comment]
Closing Issue
