### ISSUE TITLE
Ajout_Pages_Transcriptions_Individuelles_TXT

### ISSUE THREAD

**Issue by Arsene-Gery** [savaij/HN-2023-guesclin#31]
ajoutez vos transcriptions finales au format TXT

**Comment by Arsene-Gery** [comment]
Arsene = DONE (pull request #34)

**Comment by franzisss** [comment]
francesca = DONE (pull request #38)

**Comment by Arsene-Gery** [comment]
Albina = DONE (pull request #50)

**Comment by Arsene-Gery** [comment]
ALL DOCUMENTS UPLOADED

**Comment by Arsene-Gery** [comment]
Closing Issue
