### ISSUE TITLE
Lettrines

### ISSUE THREAD

**Issue by franzisss** [savaij/HN-2023-guesclin#4]
Comment transcrire les Lettrines ?
Doit-on définir une nouvelle zone de texte ou simplement corriger les lignes de texte ?

**Comment by savaij** [comment]
Aucune idée! (juste pour voir comment ça marche)

**Comment by Arsene-Gery** [comment]
Transcription des lettrines comme des majuscules (d'apres le travail d'Ariane Pinche). 
Lignes corrigées.

**Comment by franzisss** [comment]
closing issue
